package org.tonykuo.persistence.entity;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Generated 2016/6/23 下午 03:34:34 by Hibernate Tools 4.3.1.Final
 * HanksMasterUser generated by hbm2java
 * @author tonykuo
 *
 */
@Entity
@Table(name="HANKS_MASTER_USER"
    ,catalog="HANKS"
)
public class HanksMasterUser  implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    
    private HanksMasterUserId id;
    private Byte paidType;
    private Byte subType;
    private String token;
    private Date createDate;

    public HanksMasterUser() {
    }
	
    public HanksMasterUser(HanksMasterUserId id, Date createDate) {
       this.id = id;
       this.createDate = createDate;
    }

    public HanksMasterUser(HanksMasterUserId id, Byte paidType, Byte subType, String token, Date createDate) {
       this.id = id;
       this.paidType = paidType;
       this.subType = subType;
       this.token = token;
       this.createDate = createDate;
    }
   
    @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="masterUserId", column=@Column(name="master_user_id", nullable=false, length=60) ), 
        @AttributeOverride(name="msisdn", column=@Column(name="msisdn", nullable=false, length=60) ) } )
    public HanksMasterUserId getId() {
        return this.id;
    }
    
    public void setId(HanksMasterUserId id) {
        this.id = id;
    }
    
    @Column(name="paid_type")
    public Byte getPaidType() {
        return this.paidType;
    }
    
    public void setPaidType(Byte paidType) {
        this.paidType = paidType;
    }
    
    @Column(name="sub_type")
    public Byte getSubType() {
        return this.subType;
    }
    
    public void setSubType(Byte subType) {
        this.subType = subType;
    }
    
    @Column(name="token", length=60)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	     StringBuffer buffer = new StringBuffer();
         buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
         buffer.append("]");
         return buffer.toString();
     }

}

